api_platform:
    title: 'API tmdb'
    description : 'Une api avec 5 endpoints qui utilise elle même l api tmdb '
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-path+json']
    swagger:
        versions: [3]